[colors]
[colors.primary]
background = '#181616'
foreground = '#c5c9c5'

[colors.normal]
black   = '#0d0c0c'
red     = '#c4746e'
green   = '#87a987'
yellow  = '#c4b28a'
blue    = '#8ba4b0'
magenta = '#8992a7'
cyan    = '#8ea4a2'
white   = '#a6a69c'

[colors.bright]
black   = '#625e5a'
red     = '#c4746e'
green   = '#87a987'
yellow  = '#c4b28a'
blue    = '#8ba4b0'
magenta = '#a292a3'
cyan    = '#8ea4a2'
white   = '#c5c9c5'

[colors.selection]
background = '#282727'
foreground = '#c5c9c5'

[[colors.indexed_colors]]
index = 16
color = '#b6927b'

[[colors.indexed_colors]]
index = 17
color = '#c4746e'